export type Product = {
  slug: string;
  name: string;
  category: string;
  price: string;
  description: string;
  strengthMg: number;
  volumeMl: number;
  storage?: string;
  aliases?: string[];
};

const vialStorage = "Store refrigerated at 2-8C. Protect from light.";

export const products: Product[] = [
  {
    slug: "cjc-1295-with-dac",
    name: "CJC-1295 with DAC",
    category: "Growth Hormone Axis",
    price: "$129.00",
    description: "Long-acting GHRH analog positioned for extended growth hormone axis research.",
    strengthMg: 5,
    volumeMl: 10,
    storage: vialStorage,
    aliases: ["cjc1295 with dac", "cjc 1295 dac"],
  },
  {
    slug: "cjc-1295-without-dac-ipa",
    name: "CJC-1295 without DAC + IPA",
    category: "Growth Hormone Axis",
    price: "$75.00",
    description:
      "Short-acting CJC and ipamorelin blend selected for pulsatile growth hormone pathway studies.",
    strengthMg: 5,
    volumeMl: 10,
    storage: vialStorage,
    aliases: ["cjc1295 without dac +ipa 5mg", "cjc no dac ipa"],
  },
  {
    slug: "mots-c",
    name: "MOTS-c",
    category: "Metabolic Signaling",
    price: "$35.00",
    description: "Mitochondrial-derived peptide used in cellular energy and metabolic signaling models.",
    strengthMg: 10,
    volumeMl: 10,
    storage: vialStorage,
  },
  {
    slug: "tesamorelin",
    name: "Tesamorelin",
    category: "Growth Hormone Axis",
    price: "$75.00",
    description: "GHRH analog used in endocrine, body-composition, and growth hormone axis studies.",
    strengthMg: 10,
    volumeMl: 10,
    storage: vialStorage,
  },
  {
    slug: "slu-pp-322",
    name: "SLU-PP-322",
    category: "Metabolic Signaling",
    price: "$179.00",
    description: "Emerging metabolic pathway compound presented for exploratory laboratory protocols.",
    strengthMg: 5,
    volumeMl: 10,
    storage: vialStorage,
    aliases: ["slu-pp-322 - 5mg"],
  },
  {
    slug: "tb-500",
    name: "TB-500",
    category: "Repair / Recovery",
    price: "$109.00",
    description: "Thymosin beta-4 fragment used in tissue-repair and recovery signaling models.",
    strengthMg: 10,
    volumeMl: 10,
    storage: vialStorage,
    aliases: ["tb500"],
  },
  {
    slug: "ipamorelin",
    name: "Ipamorelin",
    category: "Growth Hormone Axis",
    price: "$99.00",
    description: "Selective ghrelin receptor agonist used in growth hormone release pathway research.",
    strengthMg: 5,
    volumeMl: 10,
    storage: vialStorage,
  },
  {
    slug: "nad-plus",
    name: "NAD+",
    category: "Metabolic Signaling",
    price: "$79.00",
    description:
      "Nicotinamide adenine dinucleotide format selected at 500 mg for mitochondrial and energy-system research.",
    strengthMg: 500,
    volumeMl: 10,
    storage: vialStorage,
    aliases: ["nad", "nad+ 100 500 1000mg"],
  },
  {
    slug: "kisspeptin",
    name: "Kisspeptin",
    category: "Specialty Signaling",
    price: "$39.00",
    description: "Peptide used in reproductive endocrine signaling and hypothalamic axis research.",
    strengthMg: 10,
    volumeMl: 10,
    storage: vialStorage,
    aliases: ["kisspetin"],
  },
  {
    slug: "klow-80",
    name: "KLOW 80",
    category: "Specialty Signaling",
    price: "$109.00",
    description: "High-strength blend format positioned for advanced signaling and stack-based research.",
    strengthMg: 80,
    volumeMl: 10,
    storage: vialStorage,
    aliases: ["klow80", "klow 80"],
  },
  {
    slug: "glow-70",
    name: "GLOW 70",
    category: "Specialty Signaling",
    price: "$99.00",
    description: "Signature blend format positioned for appearance, recovery, and signaling model protocols.",
    strengthMg: 70,
    volumeMl: 10,
    storage: vialStorage,
    aliases: ["glow70", "glow 70"],
  },
  {
    slug: "bpc157",
    name: "BPC-157",
    category: "Repair / Recovery",
    price: "$89.00",
    description: "Synthetic peptide used in tissue signaling, repair, and regenerative research models.",
    strengthMg: 10,
    volumeMl: 10,
    storage: vialStorage,
    aliases: ["bpc-157"],
  },
  {
    slug: "tirzepatide",
    name: "Tirzepatide",
    category: "Metabolic Signaling",
    price: "$239.00",
    description: "Dual-pathway incretin analog selected for glucose regulation and appetite model research.",
    strengthMg: 10,
    volumeMl: 10,
    storage: vialStorage,
    aliases: ["trizepatide"],
  },
  {
    slug: "semaglutide",
    name: "Semaglutide",
    category: "Metabolic Signaling",
    price: "$219.00",
    description: "GLP-1 receptor analog used in metabolic, satiety, and signaling investigations.",
    strengthMg: 5,
    volumeMl: 10,
    storage: vialStorage,
    aliases: ["semaglutide"],
  },
  {
    slug: "retatrutide",
    name: "Retatrutide",
    category: "Metabolic Signaling",
    price: "$109.00",
    description: "Triple-agonist research analog positioned for next-generation metabolic pathway studies.",
    strengthMg: 10,
    volumeMl: 10,
    storage: vialStorage,
  },
  {
    slug: "survodutide",
    name: "Survodutide",
    category: "Metabolic Signaling",
    price: "$289.00",
    description: "Multi-receptor metabolic analog used in liver, energy, and weight-regulation models.",
    strengthMg: 10,
    volumeMl: 10,
    storage: vialStorage,
  },
  {
    slug: "oxytocin",
    name: "Oxytocin",
    category: "Specialty Signaling",
    price: "$89.00",
    description: "Neuropeptide used in behavioral, social, and signaling research contexts.",
    strengthMg: 10,
    volumeMl: 10,
    storage: vialStorage,
  },
  {
    slug: "semax",
    name: "Semax",
    category: "Neuromodulation",
    price: "$99.00",
    description: "Neuropeptide analog commonly studied in cognitive, focus, and neuroplasticity models.",
    strengthMg: 30,
    volumeMl: 10,
    storage: vialStorage,
  },
  {
    slug: "igf-1-lr3",
    name: "IGF-1 LR3",
    category: "Growth Hormone Axis",
    price: "$79.00",
    description: "Long-acting IGF analog used in anabolic and growth-factor signaling studies.",
    strengthMg: 1,
    volumeMl: 10,
    storage: vialStorage,
  },
  {
    slug: "ss-31",
    name: "SS-31",
    category: "Repair / Recovery",
    price: "$49.00",
    description: "Mitochondria-targeted peptide used in oxidative stress and recovery signaling models.",
    strengthMg: 10,
    volumeMl: 10,
    storage: vialStorage,
  },
  {
    slug: "selank",
    name: "Selank",
    category: "Neuromodulation",
    price: "$99.00",
    description: "Synthetic neuropeptide explored in stress-response and neuromodulation studies.",
    strengthMg: 30,
    volumeMl: 10,
    storage: vialStorage,
  },
  {
    slug: "pt-141",
    name: "PT-141",
    category: "Specialty Signaling",
    price: "$45.00",
    description: "Melanocortin pathway peptide used in signaling and response-based laboratory research.",
    strengthMg: 10,
    volumeMl: 10,
    storage: vialStorage,
    aliases: ["pt141"],
  },
  {
    slug: "sermorelin-acetate",
    name: "Sermorelin Acetate",
    category: "Growth Hormone Axis",
    price: "$109.00",
    description: "GHRH fragment used in pituitary signaling and growth hormone secretion studies.",
    strengthMg: 5,
    volumeMl: 10,
    storage: vialStorage,
  },
];

export function getProductBySlug(slug?: string) {
  return products.find((product) => product.slug === slug);
}
