export type Product = {
  slug: string;
  name: string;
  category: string;
  price: string;
  description: string;
  formatLabel: string;
  strengthMg?: number | null;
  volumeMl?: number | null;
  storage?: string;
  aliases?: string[];
  benchmarkRetailPrice?: string;
  benchmarkSource?: string;
};

const competitorShopSource = "https://superhumanpeptide.com/shop/";
const vialStorage = "Store refrigerated at 2-8C. Protect from light.";
const dryStorage = "Store in a cool, dry place away from heat, humidity, and direct light.";
const roomTempStorage = "Store at controlled room temperature and keep sealed when not in use.";

export const products: Product[] = [
  {
    slug: "cjc-1295-with-dac",
    name: "CJC-1295 with DAC",
    category: "Growth Hormone",
    price: "$129.00",
    description: "Long-acting GHRH analog positioned for extended growth hormone axis research.",
    formatLabel: "5 mg / 10 mL vial",
    strengthMg: 5,
    volumeMl: 10,
    storage: vialStorage,
    aliases: ["cjc1295 with dac", "cjc 1295 dac"],
  },
  {
    slug: "cjc-1295-ipamorelin",
    name: "CJC-1295 / Ipamorelin",
    category: "Growth Hormone",
    price: "$71.00",
    description: "Matched CJC and ipamorelin blend used for pulse-style growth hormone signaling research.",
    formatLabel: "5 mg / 5 mg blend · 10 mL vial",
    volumeMl: 10,
    storage: vialStorage,
    aliases: ["cjc1295 without dac +ipa 5mg", "cjc no dac ipa", "cjc 1295 ipamorelin 5 5mg"],
    benchmarkRetailPrice: "$95.00",
    benchmarkSource: competitorShopSource,
  },
  {
    slug: "ipamorelin",
    name: "Ipamorelin",
    category: "Growth Hormone",
    price: "$63.00",
    description: "Selective ghrelin receptor agonist used in growth hormone release pathway research.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: vialStorage,
    benchmarkRetailPrice: "$85.00",
    benchmarkSource: competitorShopSource,
  },
  {
    slug: "tesamorelin",
    name: "Tesamorelin",
    category: "Growth Hormone",
    price: "$67.00",
    description: "GHRH analog used in endocrine, body-composition, and growth hormone axis studies.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: vialStorage,
    benchmarkRetailPrice: "$90.00",
    benchmarkSource: competitorShopSource,
  },
  {
    slug: "sermorelin",
    name: "Sermorelin",
    category: "Growth Hormone",
    price: "$63.00",
    description: "GHRH fragment used in pituitary signaling and growth hormone secretion studies.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: vialStorage,
    aliases: ["sermorelin acetate"],
    benchmarkRetailPrice: "$85.00",
    benchmarkSource: competitorShopSource,
  },
  {
    slug: "ghrp-6",
    name: "GHRP-6",
    category: "Growth Hormone",
    price: "$30.00",
    description: "Growth hormone secretagogue used in appetite and peptide signaling research.",
    formatLabel: "5 mg / 10 mL vial",
    strengthMg: 5,
    volumeMl: 10,
    storage: vialStorage,
    benchmarkRetailPrice: "$40.00",
    benchmarkSource: competitorShopSource,
  },
  {
    slug: "igf-1-lr3",
    name: "IGF-1 LR3",
    category: "Growth Hormone",
    price: "$75.00",
    description: "Long-acting IGF analog used in anabolic and growth-factor signaling studies.",
    formatLabel: "1 mg / 10 mL vial",
    strengthMg: 1,
    volumeMl: 10,
    storage: vialStorage,
    benchmarkRetailPrice: "$100.00",
    benchmarkSource: competitorShopSource,
  },
  {
    slug: "mots-c",
    name: "MOTS-c",
    category: "GLP & Metabolic",
    price: "$30.00",
    description: "Mitochondrial-derived peptide used in cellular energy and metabolic signaling models.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: vialStorage,
    benchmarkRetailPrice: "$40.00",
    benchmarkSource: competitorShopSource,
  },
  {
    slug: "nad-plus",
    name: "NAD+",
    category: "GLP & Metabolic",
    price: "$75.00",
    description: "Nicotinamide adenine dinucleotide format selected for mitochondrial and energy-system research.",
    formatLabel: "500 mg / 10 mL vial",
    strengthMg: 500,
    volumeMl: 10,
    storage: vialStorage,
    aliases: ["nad", "nad+ 100 500 1000mg"],
    benchmarkRetailPrice: "$100.00",
    benchmarkSource: competitorShopSource,
  },
  {
    slug: "tirzepatide",
    name: "Tirzepatide",
    category: "GLP & Metabolic",
    price: "$135.00",
    description: "Dual-pathway incretin analog positioned for appetite, glucose, and metabolic pathway research.",
    formatLabel: "30 mg peptide vial",
    strengthMg: 30,
    storage: vialStorage,
    aliases: ["trizepatide", "glp2 tirzepatide"],
    benchmarkRetailPrice: "$180.00",
    benchmarkSource: competitorShopSource,
  },
  {
    slug: "semaglutide",
    name: "Semaglutide",
    category: "GLP & Metabolic",
    price: "$219.00",
    description: "GLP-1 receptor analog used in metabolic, satiety, and signaling investigations.",
    formatLabel: "5 mg / 10 mL vial",
    strengthMg: 5,
    volumeMl: 10,
    storage: vialStorage,
  },
  {
    slug: "retatrutide",
    name: "Retatrutide",
    category: "GLP & Metabolic",
    price: "$105.00",
    description: "Triple-agonist research analog positioned for next-generation metabolic pathway studies.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: vialStorage,
    benchmarkRetailPrice: "$140.00",
    benchmarkSource: competitorShopSource,
  },
  {
    slug: "survodutide",
    name: "Survodutide",
    category: "GLP & Metabolic",
    price: "$289.00",
    description: "Multi-receptor metabolic analog used in liver, energy, and weight-regulation models.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: vialStorage,
  },
  {
    slug: "5-amino-1mq",
    name: "5 Amino 1MQ",
    category: "GLP & Metabolic",
    price: "$93.00",
    description: "Capsule-format metabolic compound positioned for body-composition and mitochondrial pathway research.",
    formatLabel: "Capsule bottle",
    storage: dryStorage,
    aliases: ["5 amino 1mq", "5 amino 1m q"],
    benchmarkRetailPrice: "$125.00",
    benchmarkSource: competitorShopSource,
  },
  {
    slug: "5-amino-1mq-60-capsules",
    name: "5 Amino 1MQ - 60 Capsules",
    category: "GLP & Metabolic",
    price: "$131.00",
    description: "Extended-count 5 Amino 1MQ bottle for metabolic and body-composition research protocols.",
    formatLabel: "60 capsules",
    storage: dryStorage,
    aliases: ["5 amino 1mq 60 pills"],
    benchmarkRetailPrice: "$175.00",
    benchmarkSource: competitorShopSource,
  },
  {
    slug: "adipotide",
    name: "Adipotide",
    category: "GLP & Metabolic",
    price: "$26.00",
    description: "Investigational peptide studied in adipose-targeting and weight-regulation models.",
    formatLabel: "2 mg / 10 mL vial",
    strengthMg: 2,
    volumeMl: 10,
    storage: vialStorage,
    benchmarkRetailPrice: "$35.00",
    benchmarkSource: competitorShopSource,
  },
  {
    slug: "aod-9604",
    name: "AOD-9604",
    category: "GLP & Metabolic",
    price: "$56.00",
    description: "Fragment peptide commonly included in lipolysis and metabolic support research.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: vialStorage,
    benchmarkRetailPrice: "$75.00",
    benchmarkSource: competitorShopSource,
  },
  {
    slug: "slu-pp-322",
    name: "SLU-PP-322",
    category: "GLP & Metabolic",
    price: "$179.00",
    description: "Emerging metabolic pathway compound presented for exploratory laboratory protocols.",
    formatLabel: "5 mg / 10 mL vial",
    strengthMg: 5,
    volumeMl: 10,
    storage: vialStorage,
    aliases: ["slu-pp-322 - 5mg"],
  },
  {
    slug: "slu-pp-332-capsules",
    name: "SLU-PP-332",
    category: "GLP & Metabolic",
    price: "$67.00",
    description: "Capsule-format metabolic research compound used in endurance and mitochondrial pathway studies.",
    formatLabel: "100 capsules · 250 mcg each",
    storage: dryStorage,
    aliases: ["slu-pp-332 pills 250mcg 100 pills"],
    benchmarkRetailPrice: "$90.00",
    benchmarkSource: competitorShopSource,
  },
  {
    slug: "tesofensine-capsules",
    name: "Tesofensine",
    category: "GLP & Metabolic",
    price: "$112.00",
    description: "Capsule-format monoamine reuptake inhibitor analog positioned for appetite and metabolic research.",
    formatLabel: "100 capsules · 500 mcg each",
    storage: dryStorage,
    aliases: ["tesofensine 500mcg 100 pills"],
    benchmarkRetailPrice: "$150.00",
    benchmarkSource: competitorShopSource,
  },
  {
    slug: "tb-500",
    name: "TB-500",
    category: "Recovery & Repair",
    price: "$109.00",
    description: "Thymosin beta-4 fragment used in tissue-repair and recovery signaling models.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: vialStorage,
    aliases: ["tb500"],
  },
  {
    slug: "bpc-157",
    name: "BPC-157",
    category: "Recovery & Repair",
    price: "$89.00",
    description: "Synthetic peptide used in tissue signaling, repair, and regenerative research models.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: vialStorage,
    aliases: ["bpc157", "bpc-157"],
  },
  {
    slug: "bpc-157-capsules",
    name: "BPC-157 Capsules",
    category: "Recovery & Repair",
    price: "$105.00",
    description: "Oral capsule format of BPC-157 presented for barrier, gut, and recovery pathway research.",
    formatLabel: "100 capsules · 500 mcg each",
    storage: dryStorage,
    aliases: ["bpc 157 500mcg 100 pills"],
    benchmarkRetailPrice: "$140.00",
    benchmarkSource: competitorShopSource,
  },
  {
    slug: "bpc-157-tb-500",
    name: "BPC-157 / TB-500",
    category: "Recovery & Repair",
    price: "$75.00",
    description: "Combination recovery blend used in connective tissue and repair signaling studies.",
    formatLabel: "5 mg / 5 mg blend · 10 mL vial",
    volumeMl: 10,
    storage: vialStorage,
    aliases: ["bpc 157 tb500 5 5mg"],
    benchmarkRetailPrice: "$100.00",
    benchmarkSource: competitorShopSource,
  },
  {
    slug: "frag-176-191",
    name: "Frag 176-191",
    category: "Recovery & Repair",
    price: "$37.00",
    description: "Growth hormone fragment used in composition and lipolysis-oriented research.",
    formatLabel: "5 mg / 10 mL vial",
    strengthMg: 5,
    volumeMl: 10,
    storage: vialStorage,
    benchmarkRetailPrice: "$50.00",
    benchmarkSource: competitorShopSource,
  },
  {
    slug: "ghk-cu",
    name: "GHK-Cu",
    category: "Recovery & Repair",
    price: "$48.00",
    description: "Copper peptide used in repair, cosmetic biology, and skin-focused pathway research.",
    formatLabel: "100 mg / 10 mL vial",
    strengthMg: 100,
    volumeMl: 10,
    storage: vialStorage,
    benchmarkRetailPrice: "$65.00",
    benchmarkSource: competitorShopSource,
  },
  {
    slug: "glutathione",
    name: "Glutathione",
    category: "Recovery & Repair",
    price: "$71.00",
    description: "Antioxidant support compound commonly used in detoxification and oxidative-stress studies.",
    formatLabel: "1500 mg / 10 mL vial",
    strengthMg: 1500,
    volumeMl: 10,
    storage: vialStorage,
    benchmarkRetailPrice: "$95.00",
    benchmarkSource: competitorShopSource,
  },
  {
    slug: "ll-37",
    name: "LL-37",
    category: "Recovery & Repair",
    price: "$52.00",
    description: "Antimicrobial peptide used in innate immunity, wound-response, and barrier research.",
    formatLabel: "5 mg / 10 mL vial",
    strengthMg: 5,
    volumeMl: 10,
    storage: vialStorage,
    benchmarkRetailPrice: "$70.00",
    benchmarkSource: competitorShopSource,
  },
  {
    slug: "ss-31",
    name: "SS-31",
    category: "Recovery & Repair",
    price: "$45.00",
    description: "Mitochondria-targeted peptide used in oxidative stress and recovery signaling models.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: vialStorage,
    benchmarkRetailPrice: "$60.00",
    benchmarkSource: competitorShopSource,
  },
  {
    slug: "semax",
    name: "Semax",
    category: "Cognitive & Focus",
    price: "$37.00",
    description: "Neuropeptide analog commonly studied in attention, memory, and neuroplasticity models.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: vialStorage,
    benchmarkRetailPrice: "$50.00",
    benchmarkSource: competitorShopSource,
  },
  {
    slug: "selank",
    name: "Selank",
    category: "Cognitive & Focus",
    price: "$37.00",
    description: "Synthetic neuropeptide explored in stress-response and neuromodulation studies.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: vialStorage,
    benchmarkRetailPrice: "$50.00",
    benchmarkSource: competitorShopSource,
  },
  {
    slug: "dsip",
    name: "DSIP",
    category: "Cognitive & Focus",
    price: "$33.00",
    description: "Delta sleep-inducing peptide used in sleep, stress, and circadian research models.",
    formatLabel: "5 mg / 10 mL vial",
    strengthMg: 5,
    volumeMl: 10,
    storage: vialStorage,
    benchmarkRetailPrice: "$45.00",
    benchmarkSource: competitorShopSource,
  },
  {
    slug: "epithalon",
    name: "Epithalon",
    category: "Longevity & Immune",
    price: "$33.00",
    description: "Tetrapeptide used in aging, telomere, and circadian rhythm research contexts.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: vialStorage,
    benchmarkRetailPrice: "$45.00",
    benchmarkSource: competitorShopSource,
  },
  {
    slug: "thymalin",
    name: "Thymalin",
    category: "Longevity & Immune",
    price: "$82.00",
    description: "Thymic peptide used in immune function and healthy-aging laboratory studies.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: vialStorage,
    benchmarkRetailPrice: "$110.00",
    benchmarkSource: competitorShopSource,
  },
  {
    slug: "thymosin-alpha-1",
    name: "Thymosin Alpha 1",
    category: "Longevity & Immune",
    price: "$82.00",
    description: "Immune-modulating peptide used in infection, inflammation, and oncology pathway research.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: vialStorage,
    benchmarkRetailPrice: "$110.00",
    benchmarkSource: competitorShopSource,
  },
  {
    slug: "follistatin",
    name: "Follistatin",
    category: "Specialty Research",
    price: "$75.00",
    description: "Binding protein analog used in myostatin and muscle-signaling research.",
    formatLabel: "1 mg / 10 mL vial",
    strengthMg: 1,
    volumeMl: 10,
    storage: vialStorage,
    benchmarkRetailPrice: "$100.00",
    benchmarkSource: competitorShopSource,
  },
  {
    slug: "kisspeptin",
    name: "Kisspeptin",
    category: "Specialty Research",
    price: "$33.00",
    description: "Peptide used in reproductive endocrine signaling and hypothalamic axis research.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: vialStorage,
    aliases: ["kisspetin"],
    benchmarkRetailPrice: "$45.00",
    benchmarkSource: competitorShopSource,
  },
  {
    slug: "klow-80",
    name: "KLOW 80",
    category: "Specialty Research",
    price: "$105.00",
    description: "High-strength blend format positioned for advanced signaling and stack-based research.",
    formatLabel: "80 mg / 10 mL vial",
    strengthMg: 80,
    volumeMl: 10,
    storage: vialStorage,
    aliases: ["klow80", "klow 80"],
    benchmarkRetailPrice: "$140.00",
    benchmarkSource: competitorShopSource,
  },
  {
    slug: "glow-70",
    name: "GLOW 70",
    category: "Specialty Research",
    price: "$90.00",
    description: "Signature blend format positioned for appearance, recovery, and signaling model protocols.",
    formatLabel: "70 mg / 10 mL vial",
    strengthMg: 70,
    volumeMl: 10,
    storage: vialStorage,
    aliases: ["glow70", "glow 70"],
    benchmarkRetailPrice: "$120.00",
    benchmarkSource: competitorShopSource,
  },
  {
    slug: "kpv",
    name: "KPV",
    category: "Specialty Research",
    price: "$45.00",
    description: "Tripeptide used in inflammation, barrier, and immune-response research.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: vialStorage,
    aliases: ["kpv 10mg"],
    benchmarkRetailPrice: "$60.00",
    benchmarkSource: competitorShopSource,
  },
  {
    slug: "oxytocin",
    name: "Oxytocin",
    category: "Specialty Research",
    price: "$22.00",
    description: "Neuropeptide used in behavioral, social, and signaling research contexts.",
    formatLabel: "2 mg / 10 mL vial",
    strengthMg: 2,
    volumeMl: 10,
    storage: vialStorage,
    benchmarkRetailPrice: "$30.00",
    benchmarkSource: competitorShopSource,
  },
  {
    slug: "pt-141",
    name: "PT-141",
    category: "Specialty Research",
    price: "$41.00",
    description: "Melanocortin pathway peptide used in signaling and response-based laboratory research.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: vialStorage,
    aliases: ["pt141"],
    benchmarkRetailPrice: "$55.00",
    benchmarkSource: competitorShopSource,
  },
  {
    slug: "vip",
    name: "VIP",
    category: "Specialty Research",
    price: "$90.00",
    description: "Vasoactive intestinal peptide used in inflammation, vascular, and immune signaling research.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: vialStorage,
    benchmarkRetailPrice: "$120.00",
    benchmarkSource: competitorShopSource,
  },
  {
    slug: "melanotan-1",
    name: "Melanotan 1",
    category: "Specialty Research",
    price: "$41.00",
    description: "Melanocortin analog used in pigmentation and UV-response pathway studies.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: vialStorage,
    benchmarkRetailPrice: "$55.00",
    benchmarkSource: competitorShopSource,
  },
  {
    slug: "melanotan-2",
    name: "Melanotan 2",
    category: "Specialty Research",
    price: "$45.00",
    description: "Melanocortin analog studied in pigmentation, appetite, and response signaling research.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: vialStorage,
    benchmarkRetailPrice: "$60.00",
    benchmarkSource: competitorShopSource,
  },
  {
    slug: "mgf",
    name: "MGF",
    category: "Specialty Research",
    price: "$33.00",
    description: "Mechano growth factor analog used in tissue adaptation and repair signaling models.",
    formatLabel: "2 mg / 10 mL vial",
    strengthMg: 2,
    volumeMl: 10,
    storage: vialStorage,
    benchmarkRetailPrice: "$45.00",
    benchmarkSource: competitorShopSource,
  },
  {
    slug: "b-12",
    name: "B-12",
    category: "Support Supplies",
    price: "$41.00",
    description: "Liquid B-12 format used as a support item alongside broader research workflows.",
    formatLabel: "10 mL liquid",
    volumeMl: 10,
    storage: roomTempStorage,
    aliases: ["b12 10ml"],
    benchmarkRetailPrice: "$55.00",
    benchmarkSource: competitorShopSource,
  },
  {
    slug: "bacteriostatic-water",
    name: "Bacteriostatic Water",
    category: "Support Supplies",
    price: "$7.00",
    description: "Companion sterile diluent commonly ordered alongside lyophilized research vials.",
    formatLabel: "10 mL sterile water",
    volumeMl: 10,
    storage: roomTempStorage,
    aliases: ["bac water", "bacteriostatic water 10ml"],
    benchmarkRetailPrice: "$10.00",
    benchmarkSource: competitorShopSource,
  },
  {
    slug: "hcg-5000iu",
    name: "HCG",
    category: "Support Supplies",
    price: "$37.00",
    description: "Gonadotropin support product used in endocrine and reproductive lab models.",
    formatLabel: "5,000 IU vial",
    storage: vialStorage,
    aliases: ["hcg 5000iu"],
    benchmarkRetailPrice: "$50.00",
    benchmarkSource: competitorShopSource,
  },
];

export function getProductBySlug(slug?: string) {
  return products.find((product) => product.slug === slug);
}

export function getProductFormat(product?: Product) {
  return product?.formatLabel ?? "To be confirmed";
}
