export type Product = {
  slug: string;
  name: string;
  category: string;
  price: string;
  description: string;
  formatLabel: string;
  strengthMg?: number | null;
  volumeMl?: number | null;
  storage?: string;
  aliases?: string[];
  benchmarkRetailPrice?: string;
};

export const products: Product[] = [
  {
    slug: "mazdutide",
    name: "Mazdutide",
    category: "GLP & Metabolic",
    price: "$129.00",
    description: "Dual-agonist metabolic research analog used in appetite, glucose, and energy regulation studies.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: "Store refrigerated at 2-8C. Protect from light.",
  },
  {
    slug: "l-carnitine",
    name: "L-Carnitine",
    category: "GLP & Metabolic",
    price: "$35.00",
    description: "Metabolic support liquid used in fatty-acid transport and performance-focused research.",
    formatLabel: "10 mL liquid",
    volumeMl: 10,
    storage: "Store at controlled room temperature and keep sealed when not in use.",
  },
  {
    slug: "mic-blend",
    name: "MIC Blend",
    category: "GLP & Metabolic",
    price: "$39.00",
    description: "Methionine, inositol, and choline blend used in lipotropic and metabolic support studies.",
    formatLabel: "10 mL liquid",
    volumeMl: 10,
    storage: "Store at controlled room temperature and keep sealed when not in use.",
  },
  {
    slug: "nmn",
    name: "NMN",
    category: "GLP & Metabolic",
    price: "$55.00",
    description: "Nicotinamide mononucleotide support compound used in energy and healthy-aging research.",
    formatLabel: "60 capsules · 500 mg each",
    storage: "Store in a cool, dry place away from heat, humidity, and direct light.",
  },
  {
    slug: "cardarine-gw501516",
    name: "Cardarine GW-501516",
    category: "GLP & Metabolic",
    price: "$55.00",
    description: "Research compound used in endurance, lipid, and metabolic signaling studies.",
    formatLabel: "60 capsules · 10 mg each",
    storage: "Store in a cool, dry place away from heat, humidity, and direct light.",
    aliases: ["gw501516", "cardarine"],
  },
  {
    slug: "sr-9009",
    name: "SR-9009",
    category: "GLP & Metabolic",
    price: "$59.00",
    description: "Research compound used in circadian, endurance, and metabolic pathway studies.",
    formatLabel: "30 mL liquid",
    volumeMl: 30,
    storage: "Store at controlled room temperature and keep sealed when not in use.",
  },
  {
    slug: "sr-9011",
    name: "SR-9011",
    category: "GLP & Metabolic",
    price: "$59.00",
    description: "Rev-erb research compound used in metabolic timing and endurance models.",
    formatLabel: "30 mL liquid",
    volumeMl: 30,
    storage: "Store at controlled room temperature and keep sealed when not in use.",
  },
  {
    slug: "aicar",
    name: "AICAR",
    category: "GLP & Metabolic",
    price: "$79.00",
    description: "AMPK-pathway research compound used in cellular energy and endurance studies.",
    formatLabel: "50 mg / 10 mL vial",
    strengthMg: 50,
    volumeMl: 10,
    storage: "Store refrigerated at 2-8C. Protect from light.",
  },
  {
    slug: "oea",
    name: "OEA",
    category: "GLP & Metabolic",
    price: "$49.00",
    description: "Oleoylethanolamide support compound used in satiety and lipid research.",
    formatLabel: "60 capsules · 300 mg each",
    storage: "Store in a cool, dry place away from heat, humidity, and direct light.",
  },
  {
    slug: "lipo-c",
    name: "Lipo-C",
    category: "GLP & Metabolic",
    price: "$45.00",
    description: "Lipotropic support blend presented for metabolic and composition-oriented research.",
    formatLabel: "10 mL liquid",
    volumeMl: 10,
    storage: "Store at controlled room temperature and keep sealed when not in use.",
  },
  {
    slug: "semaglutide",
    name: "Semaglutide",
    category: "GLP & Metabolic",
    price: "$149.00",
    description: "Higher-strength GLP-1 receptor analog used in metabolic, satiety, and signaling research workflows.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: "Store refrigerated at 2-8C. Protect from light.",
  },
  {
    slug: "tirzepatide-15mg",
    name: "Tirzepatide 15 mg",
    category: "GLP & Metabolic",
    price: "$99.00",
    description: "Mid-strength tirzepatide format used in incretin and metabolic signaling studies.",
    formatLabel: "15 mg peptide vial",
    strengthMg: 15,
    storage: "Store refrigerated at 2-8C. Protect from light.",
  },
  {
    slug: "bpc-157-ghk-cu",
    name: "BPC-157 / GHK-Cu",
    category: "Recovery & Repair",
    price: "$89.00",
    description: "Recovery blend used in barrier, tissue, and cosmetic biology research.",
    formatLabel: "10 mg / 50 mg blend · 10 mL vial",
    volumeMl: 10,
    storage: "Store refrigerated at 2-8C. Protect from light.",
  },
  {
    slug: "ghk-cu-capsules",
    name: "GHK-Cu Capsules",
    category: "Recovery & Repair",
    price: "$69.00",
    description: "Oral copper-peptide support format used in skin and recovery research workflows.",
    formatLabel: "60 capsules",
    storage: "Store in a cool, dry place away from heat, humidity, and direct light.",
  },
  {
    slug: "ara-290",
    name: "ARA-290",
    category: "Recovery & Repair",
    price: "$85.00",
    description: "Erythropoietin-derived peptide used in inflammation and nerve-repair pathway research.",
    formatLabel: "16 mg / 10 mL vial",
    strengthMg: 16,
    volumeMl: 10,
    storage: "Store refrigerated at 2-8C. Protect from light.",
  },
  {
    slug: "kpv-capsules",
    name: "KPV Capsules",
    category: "Recovery & Repair",
    price: "$59.00",
    description: "Capsule-format KPV presented for barrier and inflammation-focused protocols.",
    formatLabel: "60 capsules · 500 mcg each",
    storage: "Store in a cool, dry place away from heat, humidity, and direct light.",
  },
  {
    slug: "tb-500-ghk-cu",
    name: "TB-500 / GHK-Cu",
    category: "Recovery & Repair",
    price: "$109.00",
    description: "Recovery blend used in tissue, skin, and mobility research.",
    formatLabel: "10 mg / 50 mg blend · 10 mL vial",
    volumeMl: 10,
    storage: "Store refrigerated at 2-8C. Protect from light.",
  },
  {
    slug: "healing-repair-blend-capsules",
    name: "Healing Repair Blend Capsules",
    category: "Recovery & Repair",
    price: "$129.00",
    description: "Stacked capsule blend built around barrier, tissue, and recovery-support pathways.",
    formatLabel: "60 capsules",
    storage: "Store in a cool, dry place away from heat, humidity, and direct light.",
  },
  {
    slug: "ll-37",
    name: "LL-37",
    category: "Recovery & Repair",
    price: "$109.00",
    description: "Higher-strength antimicrobial peptide used in innate immunity, barrier, and wound-response research.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: "Store refrigerated at 2-8C. Protect from light.",
  },
  {
    slug: "glutathione-3000mg",
    name: "Glutathione 3000 mg",
    category: "Recovery & Repair",
    price: "$99.00",
    description: "Higher-strength glutathione liquid used in oxidative-stress and detoxification research.",
    formatLabel: "3000 mg / 10 mL vial",
    strengthMg: 3000,
    volumeMl: 10,
    storage: "Store refrigerated at 2-8C. Protect from light.",
  },
  {
    slug: "tb-500-20mg",
    name: "TB-500 20 mg",
    category: "Recovery & Repair",
    price: "$159.00",
    description: "Higher-strength TB-500 format for advanced recovery and tissue-response studies.",
    formatLabel: "20 mg / 10 mL vial",
    strengthMg: 20,
    volumeMl: 10,
    storage: "Store refrigerated at 2-8C. Protect from light.",
  },
  {
    slug: "dihexa",
    name: "Dihexa",
    category: "Cognitive & Focus",
    price: "$109.00",
    description: "Research compound used in synaptic plasticity and memory-focused studies.",
    formatLabel: "30 mL liquid",
    volumeMl: 30,
    storage: "Store at controlled room temperature and keep sealed when not in use.",
  },
  {
    slug: "p21",
    name: "P21",
    category: "Cognitive & Focus",
    price: "$89.00",
    description: "Neuro-support peptide used in memory and neuroplasticity research models.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: "Store refrigerated at 2-8C. Protect from light.",
  },
  {
    slug: "na-semax-amidate",
    name: "NA Semax Amidate",
    category: "Cognitive & Focus",
    price: "$45.00",
    description: "Amidated Semax format used in cognitive and neuromodulation research.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: "Store refrigerated at 2-8C. Protect from light.",
  },
  {
    slug: "na-selank-amidate",
    name: "NA Selank Amidate",
    category: "Cognitive & Focus",
    price: "$45.00",
    description: "Amidated Selank format used in stress-response and neuromodulation studies.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: "Store refrigerated at 2-8C. Protect from light.",
  },
  {
    slug: "nsi-189",
    name: "NSI-189",
    category: "Cognitive & Focus",
    price: "$79.00",
    description: "Research compound used in neurogenesis and mood-related pathway studies.",
    formatLabel: "60 capsules · 40 mg each",
    storage: "Store in a cool, dry place away from heat, humidity, and direct light.",
  },
  {
    slug: "cerebrolysin",
    name: "Cerebrolysin",
    category: "Cognitive & Focus",
    price: "$99.00",
    description: "Neuropeptide mixture used in neural support and repair-focused laboratory work.",
    formatLabel: "10 mL ampule set",
    volumeMl: 10,
    storage: "Store at controlled room temperature and keep sealed when not in use.",
  },
  {
    slug: "pinealon",
    name: "Pinealon",
    category: "Longevity & Immune",
    price: "$45.00",
    description: "Tripeptide used in neuro-aging and healthy-aging signaling research.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: "Store refrigerated at 2-8C. Protect from light.",
  },
  {
    slug: "thymogen",
    name: "Thymogen",
    category: "Longevity & Immune",
    price: "$45.00",
    description: "Immune-support peptide used in thymic and adaptive-response studies.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: "Store refrigerated at 2-8C. Protect from light.",
  },
  {
    slug: "vilon",
    name: "Vilon",
    category: "Longevity & Immune",
    price: "$45.00",
    description: "Short peptide used in healthy-aging and cellular regulation research.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: "Store refrigerated at 2-8C. Protect from light.",
  },
  {
    slug: "vesugen",
    name: "Vesugen",
    category: "Longevity & Immune",
    price: "$49.00",
    description: "Vascular-support peptide used in healthy-aging and endothelial research models.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: "Store refrigerated at 2-8C. Protect from light.",
  },
  {
    slug: "cartalax",
    name: "Cartalax",
    category: "Longevity & Immune",
    price: "$49.00",
    description: "Cartilage-support peptide used in connective tissue and longevity research.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: "Store refrigerated at 2-8C. Protect from light.",
  },
  {
    slug: "humanin",
    name: "Humanin",
    category: "Longevity & Immune",
    price: "$89.00",
    description: "Mitochondrial peptide analog used in stress-response and healthy-aging studies.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: "Store refrigerated at 2-8C. Protect from light.",
  },
  {
    slug: "epithalon-50mg",
    name: "Epithalon 50 mg",
    category: "Longevity & Immune",
    price: "$119.00",
    description: "Higher-strength epithalon format for telomere and aging-related research.",
    formatLabel: "50 mg / 10 mL vial",
    strengthMg: 50,
    volumeMl: 10,
    storage: "Store refrigerated at 2-8C. Protect from light.",
  },
  {
    slug: "mots-c",
    name: "MOTS-c",
    category: "GLP & Metabolic",
    price: "$36.00",
    description: "Mitochondrial-derived peptide used in cellular energy and metabolic signaling models.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: "Store refrigerated at 2-8C. Protect from light.",
    benchmarkRetailPrice: "$40.00",
  },
  {
    slug: "nad-plus",
    name: "NAD+",
    category: "GLP & Metabolic",
    price: "$71.00",
    description: "Nicotinamide adenine dinucleotide format selected for mitochondrial and energy-system research.",
    formatLabel: "500 mg / 10 mL vial",
    strengthMg: 500,
    volumeMl: 10,
    storage: "Store refrigerated at 2-8C. Protect from light.",
    aliases: ["nad", "nad+ 100 500 1000mg"],
    benchmarkRetailPrice: "$79.00",
  },
  {
    slug: "tirzepatide",
    name: "Tirzepatide",
    category: "GLP & Metabolic",
    price: "$162.00",
    description: "Dual-pathway incretin analog positioned for appetite, glucose, and metabolic pathway research.",
    formatLabel: "30 mg peptide vial",
    strengthMg: 30,
    storage: "Store refrigerated at 2-8C. Protect from light.",
    aliases: ["trizepatide", "glp2 tirzepatide"],
    benchmarkRetailPrice: "$180.00",
  },
  {
    slug: "retatrutide",
    name: "Retatrutide",
    category: "GLP & Metabolic",
    price: "$126.00",
    description: "Triple-agonist research analog positioned for next-generation metabolic pathway studies.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: "Store refrigerated at 2-8C. Protect from light.",
    benchmarkRetailPrice: "$140.00",
  },
  {
    slug: "survodutide",
    name: "Survodutide",
    category: "GLP & Metabolic",
    price: "$289.00",
    description: "Multi-receptor metabolic analog used in liver, energy, and weight-regulation models.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: "Store refrigerated at 2-8C. Protect from light.",
  },
  {
    slug: "5-amino-1mq",
    name: "5 Amino 1MQ",
    category: "GLP & Metabolic",
    price: "$113.00",
    description: "Capsule-format metabolic compound positioned for body-composition and mitochondrial pathway research.",
    formatLabel: "Capsule bottle",
    storage: "Store in a cool, dry place away from heat, humidity, and direct light.",
    aliases: ["5 amino 1mq", "5 amino 1m q"],
    benchmarkRetailPrice: "$125.00",
  },
  {
    slug: "5-amino-1mq-60-capsules",
    name: "5 Amino 1MQ - 60 Capsules",
    category: "GLP & Metabolic",
    price: "$158.00",
    description: "Extended-count 5 Amino 1MQ bottle for metabolic and body-composition research protocols.",
    formatLabel: "60 capsules",
    storage: "Store in a cool, dry place away from heat, humidity, and direct light.",
    aliases: ["5 amino 1mq 60 pills"],
    benchmarkRetailPrice: "$175.00",
  },
  {
    slug: "aod-9604",
    name: "AOD-9604",
    category: "GLP & Metabolic",
    price: "$47.00",
    description: "Fragment peptide commonly included in lipolysis and metabolic support research.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: "Store refrigerated at 2-8C. Protect from light.",
    benchmarkRetailPrice: "$52.49",
  },
  {
    slug: "slu-pp-332-capsules",
    name: "SLU-PP-332",
    category: "GLP & Metabolic",
    price: "$81.00",
    description: "Capsule-format metabolic research compound used in endurance and mitochondrial pathway studies.",
    formatLabel: "100 capsules · 250 mcg each",
    storage: "Store in a cool, dry place away from heat, humidity, and direct light.",
    aliases: ["slu-pp-332 pills 250mcg 100 pills"],
    benchmarkRetailPrice: "$90.00",
  },
  {
    slug: "tesofensine-capsules",
    name: "Tesofensine",
    category: "GLP & Metabolic",
    price: "$135.00",
    description: "Capsule-format monoamine reuptake inhibitor analog positioned for appetite and metabolic research.",
    formatLabel: "100 capsules · 500 mcg each",
    storage: "Store in a cool, dry place away from heat, humidity, and direct light.",
    aliases: ["tesofensine 500mcg 100 pills"],
    benchmarkRetailPrice: "$150.00",
  },
  {
    slug: "tb-500",
    name: "TB-500",
    category: "Recovery & Repair",
    price: "$109.00",
    description: "Thymosin beta-4 fragment used in tissue-repair and recovery signaling models.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: "Store refrigerated at 2-8C. Protect from light.",
    aliases: ["tb500"],
  },
  {
    slug: "bpc-157",
    name: "BPC-157",
    category: "Recovery & Repair",
    price: "$39.00",
    description: "Synthetic peptide used in tissue signaling, repair, and regenerative research models.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: "Store refrigerated at 2-8C. Protect from light.",
    aliases: ["bpc157", "bpc-157"],
    benchmarkRetailPrice: "$42.99",
  },
  {
    slug: "bpc-157-capsules",
    name: "BPC-157 Capsules",
    category: "Recovery & Repair",
    price: "$126.00",
    description: "Oral capsule format of BPC-157 presented for barrier, gut, and recovery pathway research.",
    formatLabel: "100 capsules · 500 mcg each",
    storage: "Store in a cool, dry place away from heat, humidity, and direct light.",
    aliases: ["bpc 157 500mcg 100 pills"],
    benchmarkRetailPrice: "$140.00",
  },
  {
    slug: "bpc-157-tb-500",
    name: "BPC-157 / TB-500",
    category: "Recovery & Repair",
    price: "$83.00",
    description: "Combination recovery blend used in connective tissue, recovery, and mobility-focused research studies.",
    formatLabel: "10 mg / 10 mg blend · 10 mL vial",
    volumeMl: 10,
    storage: "Store refrigerated at 2-8C. Protect from light.",
    benchmarkRetailPrice: "$92.30",
  },
  {
    slug: "ghk-cu",
    name: "GHK-Cu",
    category: "Recovery & Repair",
    price: "$51.00",
    description: "Copper peptide used in repair, cosmetic biology, and skin-focused pathway research.",
    formatLabel: "100 mg / 10 mL vial",
    strengthMg: 100,
    volumeMl: 10,
    storage: "Store refrigerated at 2-8C. Protect from light.",
    benchmarkRetailPrice: "$56.32",
  },
  {
    slug: "glutathione",
    name: "Glutathione",
    category: "Recovery & Repair",
    price: "$86.00",
    description: "Antioxidant support compound commonly used in detoxification and oxidative-stress studies.",
    formatLabel: "1500 mg / 10 mL vial",
    strengthMg: 1500,
    volumeMl: 10,
    storage: "Store refrigerated at 2-8C. Protect from light.",
    benchmarkRetailPrice: "$95.00",
  },
  {
    slug: "ss-31",
    name: "SS-31",
    category: "Recovery & Repair",
    price: "$54.00",
    description: "Mitochondria-targeted peptide used in oxidative stress and recovery signaling models.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: "Store refrigerated at 2-8C. Protect from light.",
    benchmarkRetailPrice: "$60.00",
  },
  {
    slug: "semax",
    name: "Semax",
    category: "Cognitive & Focus",
    price: "$45.00",
    description: "Neuropeptide analog commonly studied in attention, memory, and neuroplasticity models.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: "Store refrigerated at 2-8C. Protect from light.",
    benchmarkRetailPrice: "$50.00",
  },
  {
    slug: "selank",
    name: "Selank",
    category: "Cognitive & Focus",
    price: "$45.00",
    description: "Synthetic neuropeptide explored in stress-response and neuromodulation studies.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: "Store refrigerated at 2-8C. Protect from light.",
    benchmarkRetailPrice: "$50.00",
  },
  {
    slug: "epithalon",
    name: "Epithalon",
    category: "Longevity & Immune",
    price: "$41.00",
    description: "Tetrapeptide used in aging, telomere, and circadian rhythm research contexts.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: "Store refrigerated at 2-8C. Protect from light.",
    benchmarkRetailPrice: "$45.00",
  },
  {
    slug: "thymalin",
    name: "Thymalin",
    category: "Longevity & Immune",
    price: "$99.00",
    description: "Thymic peptide used in immune function and healthy-aging laboratory studies.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: "Store refrigerated at 2-8C. Protect from light.",
    benchmarkRetailPrice: "$110.00",
  },
  {
    slug: "thymosin-alpha-1",
    name: "Thymosin Alpha 1",
    category: "Longevity & Immune",
    price: "$99.00",
    description: "Immune-modulating peptide used in infection, inflammation, and oncology pathway research.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: "Store refrigerated at 2-8C. Protect from light.",
    benchmarkRetailPrice: "$110.00",
  },
  {
    slug: "kisspeptin",
    name: "Kisspeptin",
    category: "Specialty Research",
    price: "$41.00",
    description: "Peptide used in reproductive endocrine signaling and hypothalamic axis research.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: "Store refrigerated at 2-8C. Protect from light.",
    aliases: ["kisspetin"],
    benchmarkRetailPrice: "$45.00",
  },
  {
    slug: "klow-80",
    name: "KLOW 80",
    category: "Specialty Research",
    price: "$126.00",
    description: "High-strength blend format positioned for advanced signaling and stack-based research.",
    formatLabel: "80 mg / 10 mL vial",
    strengthMg: 80,
    volumeMl: 10,
    storage: "Store refrigerated at 2-8C. Protect from light.",
    aliases: ["klow80", "klow 80"],
    benchmarkRetailPrice: "$140.00",
  },
  {
    slug: "glow-70",
    name: "GLOW 70",
    category: "Specialty Research",
    price: "$97.00",
    description: "Signature blend format positioned for appearance, recovery, and signaling model protocols.",
    formatLabel: "70 mg / 10 mL vial",
    strengthMg: 70,
    volumeMl: 10,
    storage: "Store refrigerated at 2-8C. Protect from light.",
    aliases: ["glow70", "glow 70"],
    benchmarkRetailPrice: "$107.50",
  },
  {
    slug: "kpv",
    name: "KPV",
    category: "Specialty Research",
    price: "$54.00",
    description: "Tripeptide used in inflammation, barrier, and immune-response research.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: "Store refrigerated at 2-8C. Protect from light.",
    aliases: ["kpv 10mg"],
    benchmarkRetailPrice: "$60.00",
  },
  {
    slug: "pt-141",
    name: "PT-141",
    category: "Specialty Research",
    price: "$50.00",
    description: "Melanocortin pathway peptide used in signaling and response-based laboratory research.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: "Store refrigerated at 2-8C. Protect from light.",
    aliases: ["pt141"],
    benchmarkRetailPrice: "$55.00",
  },
  {
    slug: "vip",
    name: "VIP",
    category: "Specialty Research",
    price: "$108.00",
    description: "Vasoactive intestinal peptide used in inflammation, vascular, and immune signaling research.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: "Store refrigerated at 2-8C. Protect from light.",
    benchmarkRetailPrice: "$120.00",
  },
  {
    slug: "melanotan-1",
    name: "Melanotan 1",
    category: "Specialty Research",
    price: "$50.00",
    description: "Melanocortin analog used in pigmentation and UV-response pathway studies.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: "Store refrigerated at 2-8C. Protect from light.",
    benchmarkRetailPrice: "$55.00",
  },
  {
    slug: "melanotan-2",
    name: "Melanotan 2",
    category: "Specialty Research",
    price: "$54.00",
    description: "Melanocortin analog studied in pigmentation, appetite, and response signaling research.",
    formatLabel: "10 mg / 10 mL vial",
    strengthMg: 10,
    volumeMl: 10,
    storage: "Store refrigerated at 2-8C. Protect from light.",
    benchmarkRetailPrice: "$60.00",
  },
  {
    slug: "b-12",
    name: "B-12",
    category: "Support Supplies",
    price: "$38.00",
    description: "Liquid B-12 format used as a support item alongside broader research workflows.",
    formatLabel: "10 mL liquid",
    volumeMl: 10,
    storage: "Store at controlled room temperature and keep sealed when not in use.",
    aliases: ["b12 10ml"],
    benchmarkRetailPrice: "$42.49",
  },
  {
    slug: "bacteriostatic-water",
    name: "Bacteriostatic Water",
    category: "Support Supplies",
    price: "$8.00",
    description: "Companion sterile diluent commonly ordered alongside lyophilized research vials.",
    formatLabel: "10 mL sterile water",
    volumeMl: 10,
    storage: "Store at controlled room temperature and keep sealed when not in use.",
    aliases: ["bac water", "bacteriostatic water 10ml"],
    benchmarkRetailPrice: "$9.00",
  },
  {
    slug: "hcg-5000iu",
    name: "HCG",
    category: "Support Supplies",
    price: "$45.00",
    description: "Gonadotropin support product used in endocrine and reproductive lab models.",
    formatLabel: "5,000 IU vial",
    storage: "Store refrigerated at 2-8C. Protect from light.",
    aliases: ["hcg 5000iu"],
    benchmarkRetailPrice: "$50.00",
  },];

export function getProductBySlug(slug?: string) {
  return products.find((product) => product.slug === slug);
}

export function getProductFormat(product?: Product) {
  return product?.formatLabel ?? "To be confirmed";
}
